import 'package:hive_flutter/hive_flutter.dart';
import '../models/note.dart';

class DatabaseService {
  static const String _boxName = 'notes_box';

  Future<void> init() async {
    await Hive.initFlutter();
    // Registering the adapter. NoteAdapter will be generated by hive_generator.
    // If you haven't run 'flutter pub run build_runner build' yet, 
    // you might see an error for NoteAdapter.
    Hive.registerAdapter(NoteAdapter());
    await Hive.openBox<Note>(_boxName);
  }

  Box<Note> get _box => Hive.box<Note>(_boxName);

  Future<void> addNote(Note note) async {
    await _box.put(note.id, note);
  }

  List<Note> getAllNotes() {
    return _box.values.toList();
  }

  Future<void> updateNote(Note note) async {
    await note.save();
  }

  Future<void> deleteNote(String id) async {
    await _box.delete(id);
  }
}
